stages:
  - install
  - deploy

variables:
  DEPLOY_DIR: "/sources/app/dev/front"

dev_pipeline:
  stage: install
  variables:
    BASE_URL: "http://172.31.100.57:8080"
    NEXTAUTH_URL: "http://172.31.100.57:3000"
    HOST_URL: "http://172.31.100.57:3000"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    X_NONCE_AUTHENTICATE: "Ewi5To8Pf2rbIINNFp9i9g"
    CSRF_SECRET: "50FaWgdOhi9M9wyna8taR1k3ODOR8d6u"
  only:
    - develop
  tags:
    - dev
  script:
    - npm config set registry http://172.31.100.53/repository/npm-proxy/
    - rm -f package-lock.json; rm -f .npmrc; rm -rf node_modules
    - NODE_ENV=development npm install --force
    - NODE_ENV=production npm run build
  artifacts:
    paths:
      - .next
      - public
    expire_in: 1 hour

dev_deploy:
  stage: deploy
  variables:
    NODE_ENV: "production"
  only:
    - develop
  tags:
    - dev
  script:
    - echo "Deploying with NODE_ENV=$NODE_ENV..."
    - mkdir -p $DEPLOY_DIR
    - cp -r .next $DEPLOY_DIR/
    - cp -r public $DEPLOY_DIR/
    - /bin/cp -rf $DEPLOY_DIR/.next/static/ $DEPLOY_DIR/.next/standalone/.next/
    - sudo systemctl restart front-dev