stages:
  - install
  - test
  - report
  - deploy

variables:
  DEPLOY_DIR: "/sources/app/dev/front"
  PLAYWRIGHT_BROWSERS_PATH: /root/.cache/ms-playwright

default:
  image: mcr.microsoft.com/playwright:v1.43.1-jammy
  before_script:
    - npx playwright install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/ms-playwright

dev_pipeline:
  stage: install
  variables:
    BASE_URL: "http://172.31.100.57:8080"
    NEXTAUTH_URL: "http://172.31.100.57:3000"
    HOST_URL: "http://172.31.100.57:3000"
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    X_NONCE_AUTHENTICATE: "Ewi5To8Pf2rbIINNFp9i9g"
    CSRF_SECRET: "50FaWgdOhi9M9wyna8taR1k3ODOR8d6u"
    CI: true
  only:
    - develop
  tags:
    - dev
  script:
    - npm config set registry http://172.31.100.53/repository/npm-proxy/
    - rm -f package-lock.json; rm -f .npmrc; rm -rf node_modules
    - NODE_ENV=development npm install --force
    - NODE_ENV=production npm run build
  artifacts:
    paths:
      - .next
      - public
    expire_in: 1 hour

playwright_tests:
  stage: test
  only:
    - develop
  tags:
    - dev
  script:
    - npm install --force
    - npx playwright install --with-deps
    - npx playwright test --reporter=line,allure-playwright
  artifacts:
    when: always
    paths:
      - allure-results/
    reports:
      junit: junit.xml
  allow_failure: false

upload_allure:
  stage: report
  only:
    - develop
  tags:
    - dev
  dependencies:
    - playwright_tests
  script:
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - chmod 600 id_rsa
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 172.31.100.98 >> ~/.ssh/known_hosts
    - scp -i id_rsa -r allure-results/ allure@172.31.100.98:/tmp/allure-results
    - ssh -i id_rsa allure@172.31.100.98 'allure generate /tmp/allure-results -o /var/www/allure --clean'

dev_deploy:
  stage: deploy
  variables:
    NODE_ENV: "production"
  only:
    - develop
  tags:
    - dev
  script:
    - echo "Deploying with NODE_ENV=$NODE_ENV..."
    - mkdir -p $DEPLOY_DIR
    - cp -r .next $DEPLOY_DIR/
    - cp -r public $DEPLOY_DIR/
    - /bin/cp -rf $DEPLOY_DIR/.next/static/ $DEPLOY_DIR/.next/standalone/.next/
    - sudo systemctl restart front-dev
