import type { Metadata } from "next";
import { unstable_noStore as noStore } from "next/cache";
import type { ReactElement } from "react";
import "@/shared/components/baseComponents/BCTanStackGrid/tanstack-table-style.css";
import "@mantine/notifications/styles.css";
import "@mantine/dropzone/styles.css";
import "@mantine/tiptap/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/core/styles.css";
import "mantine-datatable/styles.layer.css";
import "@leenguyen/react-flip-clock-countdown/dist/index.css";
import "../globals.css";
import { I18nProviderClient } from "@/locales/client";
import { openSans } from "@/shared/constants/open-sans";
import ContextProvider from "@/shared/providers/ContextProvider";
import { EnvProvider } from "@/shared/providers/EnvProvider";
import NextAuthSessionProvider from "@/shared/providers/NextAuthProvider";
import QueryClientProvider from "@/shared/providers/QueryClientProvider";
import MantineBaseProviderClient from "@/shared/providers/mantine/MantineBaseProvider.client";

export const metadata: Metadata = {
	title: "MonoLight",
	description: "Generated by create next app",
};

export default async function RootLayout({
	params,
	children,
}: {
	params: Promise<{ locale: string }>;
	children: ReactElement;
}) {
	const { locale } = await params;

	noStore();
	return (
		<html lang="en" className={openSans.className}>
			<head>
				{/* <ColorSchemeScript nonce={nonce.nonce} /> */}
				<title />
			</head>
			<body>
				<MantineBaseProviderClient>
					<I18nProviderClient locale={locale}>
						<EnvProvider
							envs={{
								wsUrl: process.env.WS_URL,
								baseUrl: process.env.BASE_URL,
								hostUrl: process.env.HOST_URL,
								nextAuthUrl: process.env.NEXTAUTH_URL,
							}}
						>
							<QueryClientProvider>
								<ContextProvider>
									<NextAuthSessionProvider>{children}</NextAuthSessionProvider>
								</ContextProvider>
							</QueryClientProvider>
						</EnvProvider>
					</I18nProviderClient>
				</MantineBaseProviderClient>
			</body>
		</html>
	);
}
