import type { Metadata } from "next";
import { unstable_noStore as noStore } from "next/cache";
import type { ReactElement } from "react";
import "@/shared/components/baseComponents/BCTanStackGrid/tanstack-table-style.css";
import "@mantine/notifications/styles.css";
import "@mantine/dropzone/styles.css";
import "@mantine/tiptap/styles.css";
import "@mantine/dates/styles.css";
import "@leenguyen/react-flip-clock-countdown/dist/index.css";
import "../globals.css";
import "@mantine/core/styles.css";
import * as process from "node:process";
import { I18nProviderClient } from "@/locales/client";
import ICAppManagerProvider from "@/shared/components/infraComponents/ICAppManager/components/ICAppManagerProvider";
import ContextProvider from "@/shared/providers/ContextProvider";
import { EnvProvider } from "@/shared/providers/EnvProvider";
import NextAuthSessionProvider from "@/shared/providers/NextAuthProvider";
import QueryClientProvider from "@/shared/providers/QueryClientProvider";
import MantineBaseProviderClient from "@/shared/providers/mantine/MantineBaseProvider.client";
import { Manrope } from "next/font/google";

export const metadata: Metadata = {
	title: "MonoSuit",
	description: "Generated by create next app",
};

const manrope = Manrope({
	variable: "--manrope",
	display: "swap",
});

export default async function RootLayout({
	params,
	children,
}: {
	params: Promise<{ locale: string }>;
	children: ReactElement;
}) {
	const { locale } = await params;

	noStore();

	return (
		<html lang="en" className={manrope.className}>
			<body>
				<MantineBaseProviderClient>
					<I18nProviderClient locale={locale}>
						<EnvProvider
							envs={{
								wsUrl: process.env.WS_URL,
								baseUrl: process.env.BASE_URL,
								hostUrl: process.env.HOST_URL,
								nextAuthUrl: process.env.NEXTAUTH_URL,
							}}
						>
							<QueryClientProvider>
								<ContextProvider>
									<NextAuthSessionProvider>
										<ICAppManagerProvider>{children}</ICAppManagerProvider>
									</NextAuthSessionProvider>
								</ContextProvider>
							</QueryClientProvider>
						</EnvProvider>
					</I18nProviderClient>
				</MantineBaseProviderClient>
			</body>
		</html>
	);
}
