import type { Metadata } from "next";
import type { ReactElement } from "react";
import "@/shared/components/baseComponents/BCTanStackGrid/tanstack-table-style.css";
import "@mantine/notifications/styles.css";
import "@mantine/dropzone/styles.css";
import "@mantine/tiptap/styles.css";
import "@mantine/dates/styles.css";
import "@leenguyen/react-flip-clock-countdown/dist/index.css";
import "../globals.css";
import "@mantine/core/styles.css";
import * as process from "node:process";
import { I18nProviderClient } from "@/locales/client";
import ContextProvider from "@/shared/providers/ContextProvider";
import { EnvProvider } from "@/shared/providers/EnvProvider";
import NextAuthSessionProvider from "@/shared/providers/NextAuthProvider";
import QueryClientProvider from "@/shared/providers/QueryClientProvider";
import MantineBaseProvider from "@/shared/providers/mantine/MantineBaseProvider";
import { Manrope } from "next/font/google";

export const metadata: Metadata = {
	title: "Lackora",
	description: "Generated by create next app",
};

const manrope = Manrope({
	variable: "--manrope",
	display: "swap",
	preload: false,
});

export default async function RootLayout({
	params,
	children,
}: {
	params: Promise<{ locale: string }>;
	children: ReactElement;
}) {
	const { locale } = await params;

	return (
		<html lang="en" className={manrope.className}>
			<body>
				<ContextProvider>
					<MantineBaseProvider>
						<I18nProviderClient locale={locale}>
							<EnvProvider
								envs={{
									wsUrl: process.env.WS_URL,
									baseUrl: process.env.BASE_URL,
									hostUrl: process.env.HOST_URL,
									nextAuthUrl: process.env.NEXTAUTH_URL,
								}}
							>
								<QueryClientProvider>
									<NextAuthSessionProvider>{children}</NextAuthSessionProvider>
								</QueryClientProvider>
							</EnvProvider>
						</I18nProviderClient>
					</MantineBaseProvider>
				</ContextProvider>
			</body>
		</html>
	);
}
