import type { GetDiscoverySettingsParams } from "@/http/generated/models";
import { useGetDiscoverySettings } from "@/http/generated/asset-identification-discovery-settings";

const mockData = {
  results: [
    {
      id: "0cfc9273-4e19-4832-ada3-6b048a43f0aa",
      name: "web_service",
      display_name: "Web Service Detection",
      author: "MonoWatch",
      vendor: "generic",
      method: "web",
      description: "Web Service Detection Adapter",
      icon: null,
      related_module: "Discovery Settings",
      type: "none-credential",
      is_active: true,
      is_used: false,
      has_config: true,
      is_manageable: false,
      caption: "1 GateWays",
      job_type: "discovery",
      job_category: "web_service",
      tags: [],
      version: 1,
      schema: {},
      output: {},
      service_name: "web_service_discovery",
      request_queue: "web_service_discovery_request",
      response_queue: "web_service_discovery_response",
      creator: "SYSTEM",
      created_time: "2025-06-26 01:06:02",
    },
    {
      id: "75176d4b-71f1-4cb4-ab7e-ccbd15c2e784",
      name: "port_detection",
      display_name: "Port Detection",
      author: "MonoWatch",
      vendor: "generic",
      method: "generic",
      description: "TCP Port Scan Adapter",
      icon: null,
      related_module: "Discovery Settings",
      type: "none-credential",
      is_active: true,
      is_used: false,
      has_config: true,
      is_manageable: true,
      caption: "2 GateWays",
      job_type: "discovery",
      job_category: "port_scan",
      tags: [],
      version: 1,
      schema: {},
      output: {},
      service_name: "port_scan_discovery",
      request_queue: "port_scan_discovery_request",
      response_queue: "port_scan_discovery_response",
      creator: "SYSTEM",
      created_time: "2025-06-26 01:04:47",
    },
    {
      id: "e6c0a1fc-489a-4979-b02a-506bddc525b6",
      name: "cisco_ssh",
      display_name: "Cisco SSH",
      author: "MonoWatch",
      vendor: "cisco",
      method: "ssh",
      description: "Cisco SSH Discovery Adapter",
      icon: null,
      related_module: "Discovery Settings",
      type: "discovery",
      is_active: true,
      is_used: false,
      has_config: true,
      is_manageable: false,
      caption: "1 GateWays",
      job_type: "discovery",
      job_category: "cisco_ssh",
      tags: [],
      version: 1,
      schema: {},
      output: {},
      service_name: "cisco_ssh_discovery",
      request_queue: "cisco_ssh_discovery_request",
      response_queue: "cisco_ssh_discovery_response",
      creator: "SYSTEM",
      created_time: "2025-06-26 01:04:47",
    },
  ],
  total: 3,
  metadata: {
    filters: [
      {
        label: "Discovery Method",
        param: "method",
        items: [
          {
            label: "SSH",
            value: "ssh",
          },
          {
            label: "WEB",
            value: "web",
          },
          {
            label: "Generic",
            value: "generic",
          },
        ],
      },
      {
        label: "Vendor",
        param: "vendor",
        items: [
          {
            label: "Cisco",
            value: "cisco",
          },
          {
            label: "Generic",
            value: "generic",
          },
        ],
      },
    ],
  },
};
export const useDiscoverySettings = (params: GetDiscoverySettingsParams) => {
  const discoverySettingsRQ = useGetDiscoverySettings(params);
  return { discoverySettingsRQ: { ...discoverySettingsRQ, data: mockData } };
};
