export enum MonoAppProductTypeEnum {
	ENTERPRISE = "ENTERPRISE",
	STANDARD = "STANDARD",
	PROFESSIONAL = "PROFESSIONAL",
}

export enum MonoAppStatusTypeEnum {
	INACTIVE = "INACTIVE",
	ACTIVATED = "ACTIVATED",
	EXPIRED = "EXPIRED",
	INSTALLING = "INSTALLING",
	SUPPORT_LICENSE_EXPIRED = "MONOCARE LICENSE EXPIRED",
}
